/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GetMatchedRouteImport } from './routes/get-matched'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as AuthenticatedPlaydatesRouteImport } from './routes/_authenticated/playdates'
import { Route as AuthenticatedDogsRouteImport } from './routes/_authenticated/dogs'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminPetsittersRouteImport } from './routes/_authenticated/admin.petsitters'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as ApiPublicHooksScrapeDailyRouteImport } from './routes/api/public/hooks/scrape-daily'

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GetMatchedRoute = GetMatchedRouteImport.update({
  id: '/get-matched',
  path: '/get-matched',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaydatesRoute = AuthenticatedPlaydatesRouteImport.update({
  id: '/playdates',
  path: '/playdates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDogsRoute = AuthenticatedDogsRouteImport.update({
  id: '/dogs',
  path: '/dogs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPetsittersRoute =
  AuthenticatedAdminPetsittersRouteImport.update({
    id: '/admin/petsitters',
    path: '/admin/petsitters',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksScrapeDailyRoute =
  ApiPublicHooksScrapeDailyRouteImport.update({
    id: '/api/public/hooks/scrape-daily',
    path: '/api/public/hooks/scrape-daily',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/get-matched': typeof GetMatchedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/partners': typeof PartnersRoute
  '/dogs': typeof AuthenticatedDogsRoute
  '/playdates': typeof AuthenticatedPlaydatesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/petsitters': typeof AuthenticatedAdminPetsittersRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/scrape-daily': typeof ApiPublicHooksScrapeDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/get-matched': typeof GetMatchedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/partners': typeof PartnersRoute
  '/dogs': typeof AuthenticatedDogsRoute
  '/playdates': typeof AuthenticatedPlaydatesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal': typeof JournalIndexRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/petsitters': typeof AuthenticatedAdminPetsittersRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/scrape-daily': typeof ApiPublicHooksScrapeDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/events': typeof EventsRoute
  '/get-matched': typeof GetMatchedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/partners': typeof PartnersRoute
  '/_authenticated/dogs': typeof AuthenticatedDogsRoute
  '/_authenticated/playdates': typeof AuthenticatedPlaydatesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/petsitters': typeof AuthenticatedAdminPetsittersRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/scrape-daily': typeof ApiPublicHooksScrapeDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/get-matched'
    | '/how-it-works'
    | '/join'
    | '/login'
    | '/map'
    | '/partners'
    | '/dogs'
    | '/playdates'
    | '/journal/$slug'
    | '/journal/'
    | '/admin/import'
    | '/admin/petsitters'
    | '/admin/requests'
    | '/admin/'
    | '/api/public/hooks/scrape-daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/get-matched'
    | '/how-it-works'
    | '/join'
    | '/login'
    | '/map'
    | '/partners'
    | '/dogs'
    | '/playdates'
    | '/journal/$slug'
    | '/journal'
    | '/admin/import'
    | '/admin/petsitters'
    | '/admin/requests'
    | '/admin'
    | '/api/public/hooks/scrape-daily'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/events'
    | '/get-matched'
    | '/how-it-works'
    | '/join'
    | '/login'
    | '/map'
    | '/partners'
    | '/_authenticated/dogs'
    | '/_authenticated/playdates'
    | '/journal/$slug'
    | '/journal/'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/petsitters'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/'
    | '/api/public/hooks/scrape-daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EventsRoute: typeof EventsRoute
  GetMatchedRoute: typeof GetMatchedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PartnersRoute: typeof PartnersRoute
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ApiPublicHooksScrapeDailyRoute: typeof ApiPublicHooksScrapeDailyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-matched': {
      id: '/get-matched'
      path: '/get-matched'
      fullPath: '/get-matched'
      preLoaderRoute: typeof GetMatchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playdates': {
      id: '/_authenticated/playdates'
      path: '/playdates'
      fullPath: '/playdates'
      preLoaderRoute: typeof AuthenticatedPlaydatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dogs': {
      id: '/_authenticated/dogs'
      path: '/dogs'
      fullPath: '/dogs'
      preLoaderRoute: typeof AuthenticatedDogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/petsitters': {
      id: '/_authenticated/admin/petsitters'
      path: '/admin/petsitters'
      fullPath: '/admin/petsitters'
      preLoaderRoute: typeof AuthenticatedAdminPetsittersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/scrape-daily': {
      id: '/api/public/hooks/scrape-daily'
      path: '/api/public/hooks/scrape-daily'
      fullPath: '/api/public/hooks/scrape-daily'
      preLoaderRoute: typeof ApiPublicHooksScrapeDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDogsRoute: typeof AuthenticatedDogsRoute
  AuthenticatedPlaydatesRoute: typeof AuthenticatedPlaydatesRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminPetsittersRoute: typeof AuthenticatedAdminPetsittersRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDogsRoute: AuthenticatedDogsRoute,
  AuthenticatedPlaydatesRoute: AuthenticatedPlaydatesRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminPetsittersRoute: AuthenticatedAdminPetsittersRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EventsRoute: EventsRoute,
  GetMatchedRoute: GetMatchedRoute,
  HowItWorksRoute: HowItWorksRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PartnersRoute: PartnersRoute,
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  ApiPublicHooksScrapeDailyRoute: ApiPublicHooksScrapeDailyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
